libname mydata '/folders/myfolders/Assignment0' access=readonly;

TITLE "PROC CORR Example: Anscombe Quartet"; ods graphics on;
PROC CORR DATA=mydata.anscombe;
VAR X1;
WITH Y1;
TITLE2 "X1 and Y1 Correlation";
run;
PROC CORR DATA=mydata.anscombe; VAR X2;
WITH Y2;
TITLE2 "X2 and Y2 Correlation"; run;
PROC CORR DATA=mydata.anscombe; VAR X3;
WITH Y3;
TITLE2 "X3 and Y3 Correlation"; run;
PROC CORR DATA=mydata.anscombe; VAR X4;
WITH Y4;
TITLE2 "X4 and Y4 Correlation"; run;
ods graphics off;

ods graphics on;
PROC SGPLOT DATA=mydata.anscombe;
LOESS X=X1 Y=Y1 / NOMARKERS;;
REG X=X1 Y=Y1;
Title2 "X1 and Y1 Scatter Plot with LOESS and Regression";
run;
PROC SGPLOT DATA=mydata.anscombe;
LOESS X=X2 Y=Y2 / NOMARKERS;;
REG X=X2 Y=Y2;
Title2 "X2 and Y2 Scatter Plot with LOESS and Regression";
run;
PROC SGPLOT DATA=mydata.anscombe;
LOESS X=X3 Y=Y3 / NOMARKERS;;
REG X=X3 Y=Y3;
Title2 "X3 and Y3 Scatter Plot with LOESS and Regression";
run;
PROC SGPLOT DATA=mydata.anscombe;
LOESS X=X4 Y=Y4 / NOMARKERS;
REG X=X4 Y=Y4;
Title2 "X4 and Y4 Scatter Plot with LOESS and Regression";
run;
ods graphics off;

ods graphics on;
PROC SGSCATTER data=mydata.anscombe;
compare X=X1 Y=Y1 / loess reg;
Title2 "X1 and Y1 Scatter with Loess and Regression"; run;
PROC SGSCATTER data=mydata.anscombe;
compare X=X2 Y=Y2 / loess reg;
Title2 "X2 and Y2 Scatter with Loess and Regression";
run;
PROC SGSCATTER data=mydata.anscombe;
compare X=X3 Y=Y3 / loess reg;
Title2 "X3 and Y3 Scatter with Loess and Regression";
run;
PROC SGSCATTER data=mydata.anscombe;
compare X=X4 Y=Y4 / loess reg;
Title2 "X4 and Y4 Scatter with Loess and Regression";
run;
ods graphics off;